### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by chris-ball** [easingthemes/ssh-deploy#71]
I'm able to successfully connect using PuTTY from my local machine, but using the same credentials I cannot deploy, for some reason. Logs are as follows:

⚠️ [Rsync] error:  rsync exited with code 255
⚠️ [Rsync] stderr:  Warning: Permanently added '[***]:18765,[35.214.39.221]:18765' (ED25519) to the list of known hosts.
***@***: Permission denied (publickey).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]

⚠️ [Rsync] stdout:  
⚠️ [Rsync] cmd:  rsync /home/runner/work/hopemill/hopemill/ ***@***:www/chrisb222.sg-host.com/public_html/ --rsh "ssh -p 18765 -i /home/runner/.ssh/deploy_key -o StrictHostKeyChecking=no" --recursive --exclude= -rltgoDzvO
 1: 0x9da7c0 node::Abort() [/home/runner/runners/2.283.2/externals/node12/bin/node]
 2: 0xa4e219  [/home/runner/runners/2.283.2/externals/node12/bin/node]
 3: 0xba5d59  [/home/runner/runners/2.283.2/externals/node12/bin/node]
 4: 0xba7b47 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/home/runner/runners/2.283.2/externals/node12/bin/node]
 5: 0x13750d9  [/home/runner/runners/2.283.2/externals/node12/bin/node]

**Comment by aladdinding** [comment]
same error

**Comment by aladdinding** [comment]
cat id_rsa.pub >> authorized_keys

**Comment by information-security** [comment]
When I added the private key content as GitHub's secret, I removed a blank line at the end of it below `-----END OPENSSH PRIVATE KEY-----` line. This caused me to receive the same error. I recopied the private key content and left the blank line intact and it works. I am not sure why this blank line was necessary but I am pretty sure that was it. There is still a small chance that I accidentally modified other content of the file during copy/paste. So my suggestion is that when you face this error first make sure that you have correctly set your Github's secret variables.

**Comment by zhanfenghai** [comment]
> I'm able to successfully connect using PuTTY from my local machine, but using the same credentials I cannot deploy, for some reason. Logs are as follows:
> 
> ⚠️ [Rsync] error: rsync exited with code 255 ⚠️ [Rsync] stderr: Warning: Permanently added '[***]:18765,[35.214.39.221]:18765' (ED25519) to the list of known hosts. _**@**_: Permission denied (publickey). rsync: connection unexpectedly closed (0 bytes received so far) [sender] rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]
> 
> ⚠️ [Rsync] stdout: ⚠️ [Rsync] cmd: rsync /home/runner/work/hopemill/hopemill/ _**@**_:www/chrisb222.sg-host.com/public_html/ --rsh "ssh -p 18765 -i /home/runner/.ssh/deploy_key -o StrictHostKeyChecking=no" --recursive --exclude= -rltgoDzvO 1: 0x9da7c0 node::Abort() [/home/runner/runners/2.283.2/externals/node12/bin/node] 2: 0xa4e219 [/home/runner/runners/2.283.2/externals/node12/bin/node] 3: 0xba5d59 [/home/runner/runners/2.283.2/externals/node12/bin/node] 4: 0xba7b47 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/home/runner/runners/2.283.2/externals/node12/bin/node] 5: 0x13750d9 [/home/runner/runners/2.283.2/externals/node12/bin/node]

have you solve the problem,

**Comment by zhanfenghai** [comment]
> I encountered the same error. My guess is rsync used by ssh-deploy supports RSA key pair and not ED25519 key pair. I tried creating a new RSA key and it worked. Try again by generating a RSA key. (Refer https://github.com/easingthemes/ssh-deploy#1-ssh_private_key-required)

I have do it follow ablve,but it does not work

**Comment by easingthemes** [comment]
In latest updates script execution via ssh is added.

If you have ssh connection issue, try adding `SCRIPT_BEFORE: ls`. This will trigger `known_hosts` update which should help with specific connection issues.

Also it is certain way to check if issue is in connection or in rsync command.

9. SCRIPT_BEFORE (optional, default '')
Script to run on host machine before rsync. Single line or multiline commands. Execution is preformed by storing commands in .sh file and executing it via .bash over ssh

10. SCRIPT_AFTER (optional, default '')
Script to run on host machine after rsync. Rsync output is stored in $RSYNC_STDOUT env variable.

<img width="820" alt="Screenshot 2023-01-03 at 04 12 32" src="https://user-images.githubusercontent.com/2750284/210296028-313a9340-fb37-4ce4-868d-a666b720d123.png">

**Comment by BECKQuentin** [comment]
Lost more than 3 hours and not yet connected in ssh via github-actions. What's wrong with this ***** key. I test like all solution :
- add it to ` authorized_keys`
- add private & public keys in github (test all because it's very explicit where we should put the keys...)
- restart all 5 times

And .. Nothing. 
I dont understand what im doing wrong. = |

**Comment by prem1sai** [comment]
The issue is reoccurring .
@easingthemes :
Can you explain this ?

[Rsync] Starting Rsync Action: /***/runner/work/htmlgithubactions/htmlgithubactions/ to ***@***:***
[Rsync] excluding folders 
ssh: connect to host *** port 22: Connection refused

rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(231) [sender=3.2.7]

❌ [Rsync] error: 
Error: rsync exited with code 255
    at ChildProcess.<anonymous> (/***/runner/work/_actions/easingthemes/ssh-deploy/main/dist/index.js:2:2603)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  code: 255
}
❌ [Rsync] stderr: 
ssh: connect to host *** port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 2[55](https://github.com/prem1sai/htmlgithubactions/actions/runs/9097093573/job/25004108466#step:3:56)) at io.c(231) [sender=3.2.7]

❌️ [Rsync] stdout: 

❌ [Rsync] command: 
================================================================
================================================================
Error: R] rsync exited with code 255
