### ISSUE TITLE
[Rsync] error:  rsync exited with code 12

### ISSUE THREAD

**Issue by danielroccha** [easingthemes/ssh-deploy#79]
I getting this error, and already check my paths
![Screen Shot 2022-06-04 at 17 43 17](https://user-images.githubusercontent.com/20954911/172024922-6b795e9b-50c5-4988-bee0-4978b0ed8633.png)
)

**Comment by soubertone** [comment]
Me too
![image](https://user-images.githubusercontent.com/52554768/174863183-1d9ae5c1-1e27-4df7-a8f0-ba4093bf466e.png)

**Comment by ourines** [comment]
`
yum search rsync
`
`yum install -y rsync`

**Comment by chanfaya** [comment]
me too
![image](https://user-images.githubusercontent.com/49064663/199141555-3b8139f0-3c03-406a-abc0-0dd1d52d5985.png)

**Comment by easingthemes** [comment]
'rsync' is not installed on remote host.
You need to install it manually.

**Comment by easingthemes** [comment]
Recently added feature:

9. **SCRIPT_BEFORE** (optional, default '')
Script to run on host machine before rsync. Single line or multiline commands. Execution is preformed by storing commands in .sh file and executing it via .bash over ssh

```
SCRIPT_BEFORE: |
  yum search rsync
  yum install -y rsync
```

You need to run this only once, since on next deployment `rsync` will be available and there is no need to wait for re/install again
