### ISSUE TITLE
deploy fail

### ISSUE THREAD

**Issue by zhanfenghai** [easingthemes/ssh-deploy#90]
<img width="794" alt="image" src="https://user-images.githubusercontent.com/18130809/206891503-69e811d9-0d00-476e-8c88-87c3b39e7849.png">

I have already try many ways,but not work

**Comment by mkalygin** [comment]
@zhanfenghai it happens because of [this issue](https://askubuntu.com/questions/1409105/ubuntu-22-04-ssh-the-rsa-key-isnt-working-since-upgrading-from-20-04). GitHub Actions use Ubuntu Latest image.

You can solve this problem in two ways:
- Use Ubuntu 20.04 image.
- Provide additional options for SSH through `REMOTE_PORT` environment variable (that's the only way I found to provide additional options, thanks to #88).

Here are the options to solve the problem:
```
REMOTE_PORT: 22 -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa
```

**Comment by easingthemes** [comment]
For SSH options, `SSH_CMD_ARGS` is now available.

**Comment by easingthemes** [comment]
Also `SCRIPT_BEFORE: ls` can help, since it's forcing `known_hosts` update

9. SCRIPT_BEFORE (optional, default '')
Script to run on host machine before rsync. Single line or multiline commands. Execution is preformed by storing commands in .sh file and executing it via .bash over ssh
